CREATE TABLE AGENTS (
    AGENT_ID char(50) PRIMARY KEY,
    NAME char(100) NOT NULL,
    EMAIL char(100) NOT NULL
);
CREATE TABLE TRANSFERS (
    SENDER_ID char(50) NOT NULL,
    RECEIVER_ID char(50) NOT NULL
)