CREATE TABLE if not exists AGENT (
    AGENT_ID varchar(36) PRIMARY KEY,
    NAME varchar(100) NOT NULL,
    EMAIL varchar(100) NOT NULL,
    PASSWORD varchar(100) not null
);
--CREATE TABLE if not exists TRANSFERS (
--    SENDER_ID char(50) NOT NULL,
--    RECEIVER_ID char(50) NOT NULL
--);
CREATE TABLE if not exists RESOURCE_TYPE (
       RESOURCE_TYPE_ID varchar(36) PRIMARY KEY,
       NAME varchar(100) NOT NULL,
       WEIGHT varchar(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS EVENT(
    EVENT_ID varchar(36) PRIMARY KEY,
    EVENT_TYPE varchar(255) NOT NULL,
    AGENT_ID varchar(36) NOT NULL,
    TIME time NOT NULL,
    BODY varchar(5000)
);
CREATE TABLE IF NOT EXISTS OWNERSHIPS(
    AGENT_ID VARCHAR(36) primary key,
    RESOURCE text NOT NULL
);
CREATE TABLE IF NOT EXISTS CREDIT(
    AGENT_ID VARCHAR(36) PRIMARY KEY,
    RESOURCE text NOT NULL
);
CREATE TABLE IF NOT EXISTS TRANSFORM(
    TRANSFORM_ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    TRANSFORM TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS LOCATION(
    LOCATION_ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(120) NOT NULL,
    LONGITUDE NUMERIC NOT NULL,
    LATITUDE NUMERIC NOT NULL
);
create table if not exists WEIGHTS(
    TYPE VARCHAR(255) primary key,
    WEIGHT int not null
);